import 'package:flutter/material.dart';
import 'api.dart';

class FormsPage extends StatefulWidget { const FormsPage({super.key,required this.api}); final ApiClient api; @override State<FormsPage> createState()=>_FormsPageState(); }
class _FormsPageState extends State<FormsPage>{ late Future<List<dynamic>> future; @override void initState(){super.initState();future=widget.api.forms();} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Рабочие формы')),body:FutureBuilder<List<dynamic>>(future:future,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('${s.error}'));final forms=s.data??[];if(forms.isEmpty)return const Center(child:Text('Нет доступных форм'));return ListView.builder(itemCount:forms.length,itemBuilder:(c,i){final f=Map<String,dynamic>.from(forms[i]);return Card(child:ListTile(title:Text('${f['name']}'),subtitle:Text('${f['description']??''}'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>FillFormPage(api:widget.api,id:f['id'] as int))));});}));}

class FillFormPage extends StatefulWidget { const FillFormPage({super.key,required this.api,required this.id}); final ApiClient api; final int id; @override State<FillFormPage> createState()=>_FillFormPageState(); }
class _FillFormPageState extends State<FillFormPage>{ final values=<String,dynamic>{}; final controllers=<String,TextEditingController>{}; bool busy=false; @override void dispose(){for(final c in controllers.values)c.dispose();super.dispose();} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Заполнение формы')),body:FutureBuilder<Map<String,dynamic>>(future:widget.api.form(widget.id),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('${s.error}'));final data=s.data!;final fields=List<dynamic>.from(data['fields']??[]);return ListView(padding:const EdgeInsets.all(16),children:[Text('${data['form']['name']}',style:Theme.of(c).textTheme.headlineSmall),if('${data['form']['description']}'.isNotEmpty) Padding(padding:const EdgeInsets.only(top:6,bottom:12),child:Text('${data['form']['description']}')), ...fields.map((raw){final f=Map<String,dynamic>.from(raw);final key='${f['id']}';final type='${f['field_type']}';final label='${f['label']}${f['required']==1?' *':''}';if(type=='select'){final opts=List<dynamic>.from(f['options']??[]);return Padding(padding:const EdgeInsets.only(bottom:12),child:DropdownButtonFormField<String>(decoration:InputDecoration(labelText:label,border:const OutlineInputBorder()),items:opts.map((x)=>DropdownMenuItem(value:'$x',child:Text('$x'))).toList(),onChanged:(v)=>values[key]=v));}if(type=='checkbox')return SwitchListTile(title:Text(label),value:values[key]==true,onChanged:(v)=>setState(()=>values[key]=v));final ctl=controllers.putIfAbsent(key,()=>TextEditingController());return Padding(padding:const EdgeInsets.only(bottom:12),child:TextField(controller:ctl,keyboardType:type=='number'?TextInputType.number:type=='date'?TextInputType.datetime:null,maxLines:type=='textarea'?5:1,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder()),onChanged:(v)=>values[key]=v));}),const SizedBox(height:8),FilledButton(onPressed:busy?null:()async{setState(()=>busy=true);try{await widget.api.submitForm(widget.id,values);if(mounted){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Данные отправлены')));Navigator.pop(c);}}catch(e){if(mounted)ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text('$e')));}if(mounted)setState(()=>busy=false);},child:Text(busy?'Отправка…':'Отправить'))]);}));}

class NotificationsPage extends StatefulWidget{const NotificationsPage({super.key,required this.api});final ApiClient api;@override State<NotificationsPage> createState()=>_NotificationsPageState();}
class _NotificationsPageState extends State<NotificationsPage>{late Future<List<dynamic>> future;@override void initState(){super.initState();future=widget.api.notifications();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Уведомления')),body:FutureBuilder<List<dynamic>>(future:future,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('${s.error}'));final items=s.data??[];if(items.isEmpty)return const Center(child:Text('Уведомлений пока нет'));return ListView.builder(itemCount:items.length,itemBuilder:(c,i){final n=Map<String,dynamic>.from(items[i]);return ListTile(leading:Icon(n['is_read']==1?Icons.notifications_none:Icons.notifications),title:Text('${n['title']}'),subtitle:Text('${n['body']}'),onTap:()=>widget.api.markNotificationRead(n['id'] as int).then((_)=>setState(()=>future=widget.api.notifications())));});}));}
