const state={token:localStorage.getItem('website_token'),user:null};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function msg(text,bad=true){$('#message').textContent=text;$('#message').style.color=bad?'#a33':'#18733b'}
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(path,{...opts,headers});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||'Ошибка запроса');return data}
function showApp(){ $('#auth').classList.add('hidden'); $('#app').classList.remove('hidden'); $('#profile').textContent=`${state.user.username} · ${state.user.role}`;if(state.user.role==='owner'){$('#owner').classList.remove('hidden');loadOwner()} }
async function boot(){if(!state.token)return;try{state.user=await api('/api/me');showApp()}catch{localStorage.removeItem('website_token');state.token=null}}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#login').classList.toggle('hidden',b.dataset.tab!=='login');$('#register').classList.toggle('hidden',b.dataset.tab!=='register');msg('')});
$('#login').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);const d=await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});state.token=d.access_token;state.user=d.user;localStorage.setItem('website_token',state.token);showApp();msg('')}catch(x){msg(x.message)}};
$('#register').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});state.token=d.access_token;state.user={id:d.id,username:d.username,role:d.role};localStorage.setItem('website_token',state.token);showApp()}catch(x){msg(x.message)}};
$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST'})}catch{}localStorage.removeItem('website_token');location.reload()};
$('#changeUsername').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/me/username',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});state.user.username=d.username;$('#profile').textContent=`${state.user.username} · ${state.user.role}`;e.target.reset();alert('Логин изменён')}catch(x){alert(x.message)}};
$('#changePassword').onsubmit=async e=>{e.preventDefault();try{await api('/api/me/password',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});localStorage.removeItem('website_token');alert('Пароль изменён. Выполните вход заново.');location.reload()}catch(x){alert(x.message)}};
$('#genInvite').onclick=async()=>{try{const d=await api('/api/invites',{method:'POST',body:JSON.stringify({role:$('#inviteRole').value})});$('#newInvite').textContent=d.code;loadOwner()}catch(x){alert(x.message)}};
async function loadOwner(){try{const [invites,users]=await Promise.all([api('/api/invites'),api('/api/admin/users')]);$('#invites').innerHTML='<h3>Ключи</h3>'+invites.map(x=>`<div>${x.code} · ${x.role} · ${x.is_used?'использован':'свободен'}</div>`).join('');$('#users').innerHTML='<h3>Пользователи</h3>'+users.map(x=>`<div>${x.username} · ${x.role} · ${x.is_active?'активен':'заблокирован'}</div>`).join('')}catch(x){console.warn(x)}}
boot();
